title: تحریر خیال
description: تحریر شعر فارسی

author: bonyad
timezone: +03:30

url: https://bonyad.github.io/tahrir/
root: /tahrir/

static: /tahrir/static/

icon: /tahrir/static/theme/tahrir/img/icon.png

post_num: all
archive_post_num: all
feed_output: atom.xml

default_floor: ghazal
default_markup: mmd

template: tahrir

github: https://github.com/bonyad
